# Load Data

In [5]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

from IPython.display import display

In [6]:
df = pd.read_csv("/content/drive/MyDrive/dibimbing/Exam Take Home Test/Food_Delivery_Times.csv")
df.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [7]:
df.columns.tolist()

['Order_ID',
 'Distance_km',
 'Weather',
 'Traffic_Level',
 'Time_of_Day',
 'Vehicle_Type',
 'Preparation_Time_min',
 'Courier_Experience_yrs',
 'Delivery_Time_min']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    object
 3   Traffic_Level           970 non-null    object
 4   Time_of_Day             970 non-null    object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

# Data Preprocessing

## Cleaning

In [9]:
# Duplicate Value
df.duplicated().sum()

np.int64(0)

In [10]:
# Missing Value
missing_summary = pd.DataFrame({
    'Type' : df.dtypes,
    'Missing Count': df.isnull().sum(),
    'Missing Percentage (%)': df.isnull().mean() * 100
})

missing_summary = missing_summary[
    missing_summary['Missing Count'] > 0
].sort_values(
    'Missing Percentage (%)',
    ascending=False
)

missing_summary

                           Type  Missing Count  Missing Percentage (%)
Weather                  object             30                     3.0
Traffic_Level            object             30                     3.0
Time_of_Day              object             30                     3.0
Courier_Experience_yrs  float64             30                     3.0

In [11]:
## Visualisasi Distribusi Nilai pada Kolom Courier Experience
import plotly.graph_objects as go

mean_value = df['Courier_Experience_yrs'].mean()
median_value = df['Courier_Experience_yrs'].median()

fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x=df['Courier_Experience_yrs'].dropna(),
        nbinsx=10,
        name='Courier Experience'
    )
)

# Mean
fig.add_vline(
    x=mean_value,
    line_dash='dash',
    annotation_text=f'Mean = {mean_value:.2f}',
    annotation_position='top'
)

# Median
fig.add_vline(
    x=median_value,
    line_dash='dot',
    annotation_text=f'Median = {median_value:.2f}',
    annotation_position='bottom'
)

fig.update_layout(
    title='Distribution of Courier Experience',
    xaxis_title='Courier Experience (years)',
    yaxis_title='Number of Couriers',
    template='plotly_white'
)

fig.show()

In [12]:
df['Courier_Experience_yrs'].skew()

np.float64(-0.029086829121382836)

In [13]:
## Solve - Missing Value pada Kolom Numerik
data = df.copy()
data['Courier_Experience_yrs'] = df['Courier_Experience_yrs'].fillna(df['Courier_Experience_yrs'].median())
data.isna().sum()

Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs     0
Delivery_Time_min          0
dtype: int64

In [14]:
## Solve - Missing Value pada Kolom Kategorik
categorical = ['Weather', 'Traffic_Level', 'Time_of_Day']

for col in categorical:
    data[col] = data[col].fillna('Unknown')

data.isna().sum()

Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64

In [15]:
# Outlier
numeric_columns = [
    'Distance_km',
    'Preparation_Time_min',
    'Courier_Experience_yrs',
    'Delivery_Time_min'
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Distance_km,1000.0,10.059970,5.696656,0.59,5.105,10.19,15.0175,19.99
Preparation_Time_min,1000.0,16.982000,7.204553,5.00,11.000,17.00,23.0000,29.00
Courier_Experience_yrs,970.0,4.579381,2.914394,0.00,2.000,5.00,7.0000,9.00
Delivery_Time_min,1000.0,56.732000,22.070915,8.00,41.000,55.50,71.0000,153.00

In [16]:
for col in numeric_columns:

    fig = go.Figure()

    fig.add_trace(
        go.Box(
            y=data[col],
            name=col
        )
    )

    fig.update_layout(
        title=f'Distribution and Outliers - {col}',
        yaxis_title=col,
        template='plotly_white'
    )

    fig.show()

In [17]:
# Checking type of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 1000 non-null   object
 3   Traffic_Level           1000 non-null   object
 4   Time_of_Day             1000 non-null   object
 5   Vehicle_Type            1000 non-null   object
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  1000 non-null   float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 70.4+ KB

## Feature Engineering

In [18]:
# Grouping Berdasarkan Jarak Pengantaran
data['Distance_Group'] = pd.cut(
    data['Distance_km'],
    bins=[-float('inf'), 3, 7, float('inf')],
    labels=['Short', 'Medium', 'Long']
)
print(data['Distance_Group'].value_counts().sort_index())

Distance_Group
Short     144
Medium    203
Long      653
Name: count, dtype: int64

In [19]:
# Grouping Berdasarkan Lama Persiapan Pesanan
data['Preparation_Group'] = pd.qcut(
    data['Preparation_Time_min'],
    q=3,
    labels=['Fast', 'Moderate', 'Slow']
)
print(data['Preparation_Group'].value_counts().sort_index())

Preparation_Group
Fast        360
Moderate    316
Slow        324
Name: count, dtype: int64

In [20]:
# Grouping Berdasarkan Pengalaman Kurir
data['Experience_Group'] = pd.cut(
    data['Courier_Experience_yrs'],
    bins=[-1, 2, 5, float('inf')],
    labels=['Beginner', 'Intermediate', 'Experienced']
)
print(data['Experience_Group'].value_counts().sort_index())

Experience_Group
Beginner        297
Intermediate    294
Experienced     409
Name: count, dtype: int64

# Exploratory Data Analysis

## Analisis Deskriptif

In [ ]:
# Statistik Deskriptif - Numerik
print("\nStatistik deskriptif :")
print(round(data.describe(), 2))

Statistik deskriptif :
       Order_ID  Distance_km  Preparation_Time_min  Courier_Experience_yrs  \
count   1000.00      1000.00               1000.00                 1000.00
mean     500.50        10.06                 16.98                    4.59
std      288.82         5.70                  7.20                    2.87
min        1.00         0.59                  5.00                    0.00
25%      250.75         5.11                 11.00                    2.00
50%      500.50        10.19                 17.00                    5.00
75%      750.25        15.02                 23.00                    7.00
max     1000.00        19.99                 29.00                    9.00

       Delivery_Time_min
count            1000.00
mean               56.73
std                22.07
min                 8.00
25%                41.00
50%                55.50
75%                71.00
max               153.00

In [ ]:
# Statistik Deskriptif - Kategorikal
print("\nStatistik deskriptif :")
print(data.describe(include=['object', 'category']))

Statistik deskriptif :
       Weather Traffic_Level Time_of_Day Vehicle_Type Distance_Group  \
count     1000          1000        1000         1000           1000
unique       6             4           5            3              3
top      Clear        Medium     Morning         Bike           Long
freq       470           390         308          503            653

       Preparation_Group Experience_Group
count               1000             1000
unique                 3                3
top                 Fast      Experienced
freq                 360              409

## Analisis Univariat - Bivariat

### Histogram - Delivery Time
> Distribusi Lama Pengiriman

In [ ]:
fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x=data['Delivery_Time_min'],
        nbinsx=30,
        name='Delivery Time'
    )
)

fig.update_layout(
    title='Distribution of Delivery Time',
    xaxis_title='Delivery Time (minutes)',
    yaxis_title='Number of Orders',
    template='plotly_white'
)

fig.show()

### Horizontal Bar Chart - Weather

In [ ]:
weather_count = data['Weather'].value_counts().sort_values()

fig = go.Figure(
    go.Bar(
        x=weather_count.values,
        y=weather_count.index,
        orientation='h',
        text=weather_count.values,
        textposition='outside',
        texttemplate='%{text} orders',
        hovertemplate='<b>%{y}</b><br>Orders: %{x}<extra></extra>'
    )
)

# Layout
fig.update_layout(
    title='Number of Orders by Weather',
    xaxis_title='Number of Orders',
    yaxis_title='Weather',
    height=450,
    width=800,
    margin=dict(l=100, r=100, t=80, b=60)
)

fig.show()

### Horizontal Barchar - Traffic Level

In [ ]:
traffic_count = data['Traffic_Level'].value_counts().sort_values()

fig = go.Figure(
    go.Bar(
        x=traffic_count.values,
        y=traffic_count.index,
        orientation='h',
        text=traffic_count.values,
        textposition='outside',
        texttemplate='%{text}',
        hovertemplate='<b>%{y}</b><br>Count: %{x}<extra></extra>'
    )
)

# Layout
fig.update_layout(
    title='Distribution of Traffic Level',
    xaxis_title='Number of Orders',
    yaxis_title='Traffic Level',
    height=450,
    width=800,
    margin=dict(l=100, r=80, t=80, b=60)
)

fig.show()

### Line Chart - Time of Day

In [ ]:
time_order = ['Morning', 'Afternoon', 'Evening', 'Night', 'Unknown']

time_count = (
    data['Time_of_Day']
    .value_counts()
    .reindex(time_order, fill_value=0)
)

# Membuat line chart
fig = go.Figure(
    go.Scatter(
        x=time_count.index,
        y=time_count.values,
        mode='lines+markers+text',
        text=time_count.values,
        textposition='top center',
        line=dict(width=3),
        marker=dict(size=8),
        hovertemplate='<b>%{x}</b><br>Number of Orders: %{y}<extra></extra>'
    )
)

# Layout
fig.update_layout(
    title='Number of Orders by Time of Day',
    xaxis_title='Time of Day',
    yaxis_title='Number of Orders',
    height=450,
    width=800,
    margin=dict(l=70, r=70, t=80, b=60)
)

fig.show()

In [ ]:
Q1 = data['Delivery_Time_min'].quantile(0.25)
Q3 = data['Delivery_Time_min'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Tandai outlier
data['Delivery_Outlier'] = (
    (data['Delivery_Time_min'] < lower_bound) |
    (data['Delivery_Time_min'] > upper_bound)
)

print("Q1 :", Q1)
print("Q3 :", Q3)
print("IQR :", IQR)
print("Lower Bound :", lower_bound)
print("Upper Bound :", upper_bound)

print("\nJumlah outlier :", data['Delivery_Outlier'].sum())
print("Persentase outlier :",
      round(data['Delivery_Outlier'].mean() * 100, 2), "%")

Q1 : 41.0
Q3 : 71.0
IQR : 30.0
Lower Bound : -4.0
Upper Bound : 116.0

Jumlah outlier : 6
Persentase outlier : 0.6 %

In [ ]:
normal = data[data['Delivery_Outlier'] == False]
outlier = data[data['Delivery_Outlier'] == True]

fig = go.Figure()

experience_groups = ['Beginner', 'Intermediate', 'Experienced']

for group in experience_groups:

    subset = data[data['Experience_Group'] == group]

    fig.add_trace(
        go.Scatter(
            x=subset['Distance_km'],
            y=subset['Delivery_Time_min'],
            mode='markers',
            name=group,
            text=subset['Order_ID'],
            hovertemplate=
                'Order ID: %{text}<br>' +
                'Experience: ' + group + '<br>' +
                'Distance: %{x:.2f} km<br>' +
                'Delivery Time: %{y:.2f} min' +
                '<extra></extra>'
        )
    )

# Garis batas atas outlier
fig.add_hline(
    y=upper_bound,
    line_dash='dash',
    annotation_text=f'Upper Bound = {upper_bound:.2f} min',
    annotation_position='top right'
)

fig.update_layout(
    title='Distance vs Delivery Time by Courier Experience',
    xaxis_title='Distance (km)',
    yaxis_title='Delivery Time (minutes)',
    template='plotly_white',
    height=600
)

fig.show()

### Numerical Analysis
> Correlation Matrix of Numerical Columns

In [ ]:
# Heatmap

corr_cols = [
    'Distance_km',
    'Preparation_Time_min',
    'Courier_Experience_yrs',
    'Delivery_Time_min'
]

correlation = data[corr_cols].corr()

fig = go.Figure(
    go.Heatmap(
        z=correlation.values,
        x=correlation.columns,
        y=correlation.columns,
        text=correlation.round(2).values,
        texttemplate='%{text}',
        colorscale='RdBu',
        zmin=-1,
        zmax=1
    )
)

fig.update_layout(
    title='Correlation Matrix of Numerical Variables',
    template='plotly_white'
)

fig.show()

# Export Data

In [ ]:
file_name = 'Food_Delivery_Clean.xlsx'

data.to_excel(file_name, index=False)

print(f"Data berhasil diekspor ke: {file_name}")
print(f"Jumlah baris  : {data.shape[0]}")
print(f"Jumlah kolom  : {data.shape[1]}")

Data berhasil diekspor ke: Food_Delivery_Clean.xlsx
Jumlah baris  : 1000
Jumlah kolom  : 13